server: 
  port: 7001
eureka:
  instance:
    hostname: eureka7001.com
  #为了防止默认情况下将自己当做客户端来注册，所以我们要禁用
  client:
    register-with-eureka: false #表示是否将自己注册到Eureka Server上，默认为true
    fetch-registry: false       #表示是否从Eureka Server上获取注册信息，默认为true
    service-url:
      defaultZone: http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/
  server:
    enable-self-preservation: false
spring:
  application:
    name: eureka7001

